#Properties Config file
#Wed Sep 23 11:22:17 UTC 2026
motd=CIVITAS OS - Peradaban Nusantara Digital
sub-motd=mulkymalikuldhr.aternos.me | Bedrock
server-port=19132
max-players=10
gamemode=0
difficulty=0
view-distance=6
spawn-protection=0
xbox-auth=off
white-list=off
enable-query=on
auto-save=on
server-portv6=19133
enable-ipv6=on
force-gamemode=off
hardcore=off
pvp=on
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
language=eng
